---
- name: Настройка Kubernetes
  hosts: docker_hosts
  become: yes
  vars:
    namespace: "crypto-app"

  tasks:
    - name: Проверка кластера
      shell: kubectl get nodes
      become_user: ubuntu
      become: no
      register: nodes_status
      changed_when: false

    - name: Создание namespace
      shell: |
        kubectl create namespace {{ namespace }} --dry-run=client -o yaml | kubectl apply -f -
      become_user: ubuntu
      become: no

    - name: Включение metrics-server
      shell: minikube addons enable metrics-server
      become_user: ubuntu
      become: no
      changed_when: false

    - name: Статус подов
      shell: kubectl get pods -n kube-system
      become_user: ubuntu
      become: no
      register: pods_status
      changed_when: false

    - name: Результат
      debug:
        msg: |
          Kubernetes настроен
          Namespace: {{ namespace }}
          Проверка: kubectl get pods -n kube-system