---
- name: Деплой
  hosts: docker_hosts
  become: yes
  vars:
    version: "{{ version | default('1.0') }}"
    registry: "cr.yandex/crpkl4pgojohfidok157"

  tasks:
    - name: Создание рабочей папки
      file:
        path: /opt/crypto
        state: directory
        mode: '0755'

    - name: Чтение токена из локального .env файла
      delegate_to: localhost
      become: no
      shell: grep YC_TOKEN .env | cut -d '=' -f2 | tr -d '\n'
      register: local_token
      changed_when: false

    - name: Логин в Yandex Registry (используем OAuth токен)
      shell: |
        echo "{{ local_token.stdout }}" | docker login \
          --username oauth \
          --password-stdin \
          cr.yandex
      when: local_token.stdout != ""

    - name: Скачивание docker-compose.yml
      get_url:
        url: https://raw.githubusercontent.com/ChornyChay1/DevOpsCryptoBrowser/refs/heads/main/docker-compose.prod.yml
        dest: /opt/crypto/docker-compose.yml
        mode: '0644'

    - name: Копирование .env (без токена) на сервер
      copy:
        src: .env
        dest: /opt/crypto/.env
        mode: '0600'

    - name: Запуск контейнеров
      shell: |
        cd /opt/crypto
        docker compose down
        docker compose pull
        docker compose up -d
      ignore_errors: yes

    - name: Проверка
      shell: cd /opt/crypto && docker compose ps
      register: ps_result

    - name: Результат
      debug:
        msg: "{{ ps_result.stdout_lines }}"