---
- name: Порт-форвардинг
  hosts: docker_hosts
  become: yes
  tasks:
    - name: Фронтенд
      shell: |
        nohup kubectl port-forward -n crypto-app svc/frontend 30924:80 --address 0.0.0.0 > /tmp/frontend-fwd.log 2>&1 &

    - name: Бэкенд
      shell: |
        nohup kubectl port-forward -n crypto-app svc/backend 8000:8000 --address 0.0.0.0 > /tmp/backend-fwd.log 2>&1 &