apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: crypto-app
spec:
  type: NodePort        # ← меняем здесь
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30081     # ← добавляем порт