apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crypto-app-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - crypto-app
  endpoints:
  - port: "8000"
    path: /metrics
    interval: 15s